"""Calibration harness: turn lab detection results into calibrated scores.

The corpus ships expert-estimated noise scores. The only way to make them
*trustworthy* is to run the techniques in a lab (Caldera/APT29, a Defender/MDI
range) and measure what actually fires. This tool ingests those detection
results and emits an environment profile whose ``adjustments`` replace the
static estimates with calibrated values - a drop-in for ``--environment`` and
the natural feedback loop between NoiseHound and a detection lab.

Input (lab detections JSON)::

    {
      "environment": "APT29-range",
      "object_auditing_4662": true,          # optional posture flags, copied through
      "observations": [
        {"edge_type": "DCSync", "runs": 3, "detections": 3, "severity": "high",
         "signals": ["4662", "MDI: Suspected DCSync"]},
        {"edge_type": "ForceChangePassword", "runs": 5, "detections": 2, "severity": "medium"},
        {"edge_type": "HasSession", "runs": 4, "detections": 0}
      ]
    }

Scoring model, per observed edge type:

    p           = detections / runs                       (detection probability)
    lab_score   = p * severity_loudness + (1 - p) * residual
    w           = runs / (runs + smoothing)               (confidence in the lab)
    calibrated  = w * lab_score + (1 - w) * corpus_static

``lab_score`` is the expected detection cost: when it fires (probability ``p``)
the cost is the SOC severity; when it does not, a small ``residual`` reflects
that events were still generated. The shrinkage weight ``w`` keeps a 1-run
observation from overriding the corpus while letting a well-sampled one dominate
- honest about small sample sizes rather than pretending three runs is truth.
"""
from __future__ import annotations

import argparse
import json
import sys

from . import __version__
from .corpus import load_corpus

SEVERITY_LOUDNESS = {
    "info": 20,
    "low": 40,
    "medium": 65,
    "high": 85,
    "critical": 95,
}
DEFAULT_SEVERITY = "medium"
DEFAULT_RESIDUAL = 15.0        # noise floor when a technique fired no alert
DEFAULT_SMOOTHING = 3.0        # runs needed before the lab outweighs the corpus

# Posture flags passed straight through from the input into the emitted profile.
_POSTURE_KEYS = (
    "object_auditing_4662",
    "ds_change_auditing_5136",
    "edr",
    "sysmon",
    "powershell_logging_4104",
)


def _clamp(x: float) -> float:
    return max(0.0, min(100.0, x))


def calibrate_observation(
    obs: dict,
    static_score: float,
    residual: float = DEFAULT_RESIDUAL,
    smoothing: float = DEFAULT_SMOOTHING,
) -> dict:
    """Return a calibration record for one observation."""
    edge_type = obs["edge_type"]

    runs = obs.get("runs")
    detections = obs.get("detections")
    if runs is None or detections is None:
        # Fall back to a boolean 'detected' with an implicit single run.
        detected = bool(obs.get("detected", False))
        runs = 1 if runs is None else int(runs)
        detections = (1 if detected else 0) if detections is None else int(detections)

    runs = max(1, int(runs))
    detections = max(0, min(int(detections), runs))
    p = detections / runs

    severity = str(obs.get("severity", DEFAULT_SEVERITY)).strip().lower()
    loudness = SEVERITY_LOUDNESS.get(severity, SEVERITY_LOUDNESS[DEFAULT_SEVERITY])
    obs_residual = float(obs.get("residual", residual))

    lab_score = p * loudness + (1.0 - p) * obs_residual
    w = runs / (runs + smoothing)
    calibrated = _clamp(round(w * lab_score + (1.0 - w) * static_score))

    return {
        "edge_type": edge_type,
        "runs": runs,
        "detections": detections,
        "detection_rate": round(p, 3),
        "severity": severity,
        "lab_score": round(lab_score, 1),
        "static_score": round(static_score, 1),
        "confidence_weight": round(w, 3),
        "calibrated_score": calibrated,
        "delta": round(calibrated - static_score, 1),
        "signals": obs.get("signals", []),
    }


def calibrate(
    detections: dict,
    corpus,
    residual: float = DEFAULT_RESIDUAL,
    smoothing: float = DEFAULT_SMOOTHING,
) -> tuple[dict, list]:
    """Return (environment_profile, per_edge_records)."""
    records = []
    adjustments = {}
    for obs in detections.get("observations", []) or []:
        if "edge_type" not in obs:
            continue
        static, _ = corpus.static_score(obs["edge_type"])
        rec = calibrate_observation(obs, static, residual, smoothing)
        records.append(rec)
        adjustments[rec["edge_type"]] = rec["calibrated_score"]

    profile = {
        "_comment": "Generated by noisehound-calibrate v%s from lab detection results. "
                    "Pass with --environment. adjustments are calibrated per-edge scores."
                    % __version__,
        "name": detections.get("environment", "calibrated"),
    }
    for key in _POSTURE_KEYS:
        if key in detections:
            profile[key] = detections[key]
    profile["adjustments"] = adjustments
    return profile, records


def _merge_profile(base: dict, generated: dict) -> dict:
    """Overlay generated calibration onto an existing profile, preserving posture."""
    merged = dict(base)
    merged["_comment"] = generated["_comment"]
    merged["name"] = generated.get("name", base.get("name", "calibrated"))
    for key in _POSTURE_KEYS:
        if key in generated:
            merged[key] = generated[key]
    adj = dict(base.get("adjustments", {}) or {})
    adj.update(generated.get("adjustments", {}))
    merged["adjustments"] = adj
    return merged


def _render_summary(records: list) -> str:
    if not records:
        return "No observations to calibrate."
    lines = ["edge_type                 runs  det   rate  static  lab  ->  calibrated  delta",
             "-" * 82]
    for r in sorted(records, key=lambda x: -x["calibrated_score"]):
        lines.append(
            "%-25s %4d %4d  %5.2f  %5.1f  %5.1f     %6d   %+6.1f"
            % (r["edge_type"][:25], r["runs"], r["detections"], r["detection_rate"],
               r["static_score"], r["lab_score"], r["calibrated_score"], r["delta"])
        )
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="noisehound-calibrate",
        description="Turn lab detection results into a calibrated NoiseHound "
                    "environment profile.",
    )
    p.add_argument("--input", "-i", default=None, help="Lab detections JSON.")
    p.add_argument("--template", action="store_true",
                   help="Emit a blank lab-detections file listing every corpus edge to exercise, then exit.")
    p.add_argument("--plan", action="store_true",
                   help="Emit the machine-readable calibration plan (per edge: abuse primitive + "
                        "the exact event IDs that count as detection) for the automated harness, then exit.")
    p.add_argument("--out", "-o", default=None,
                   help="Write the environment profile here (default: stdout).")
    p.add_argument("--corpus", default=None, help="Corpus directory (default: bundled).")
    p.add_argument("--merge", default=None,
                   help="Existing profile to overlay calibration onto (preserves posture flags).")
    p.add_argument("--residual", type=float, default=DEFAULT_RESIDUAL,
                   help="Noise floor for a technique that fired no alert (default 15).")
    p.add_argument("--smoothing", type=float, default=DEFAULT_SMOOTHING,
                   help="Runs before the lab outweighs the corpus estimate (default 3).")
    p.add_argument("--quiet", action="store_true", help="Suppress the summary table on stderr.")
    p.add_argument("--version", action="version", version="noisehound-calibrate %s" % __version__)
    return p


def build_template(corpus) -> dict:
    """A blank lab-detections skeleton listing every corpus edge to exercise."""
    observations = []
    for entry in sorted(corpus, key=lambda e: e["edge_type"]):
        observations.append({
            "edge_type": entry["edge_type"],
            "runs": 0,
            "detections": 0,
            "severity": "",
            "signals": [],
        })
    return {
        "_comment": "Blank NoiseHound calibration template. For each edge, run its abuse "
                    "primitive in the lab N times, record how many fired an alert, set the "
                    "severity (info|low|medium|high|critical), and note the signals. Drop "
                    "rows you did not test. Then: noisehound-calibrate -i this.json -o env.json",
        "environment": "my-lab",
        "observations": observations,
    }


def build_plan(corpus) -> dict:
    """The automated harness's execution plan, derived from the corpus.

    For each edge it lists the abuse primitive to run and the exact event IDs a
    detection auto-collector should look for (from the corpus telemetry). The
    harness runs each abuse N times in a clean window, counts these events, and
    scores detected/runs automatically - no manual per-technique bookkeeping.
    """
    edges = []
    for entry in sorted(corpus, key=lambda e: e["edge_type"]):
        detect = []
        for t in entry.get("telemetry", []) or []:
            if t.get("source") in ("windows_security", "sysmon") and t.get("event_id") is not None:
                detect.append({
                    "source": t["source"],
                    "event_id": t["event_id"],
                    "reliability": t.get("reliability"),
                    "default_enabled": t.get("default_enabled", True),
                })
        edges.append({
            "edge_type": entry["edge_type"],
            "mitre_technique": entry.get("mitre_technique"),
            "abuse_primitive": entry.get("abuse_primitive", ""),
            "detect_events": detect,
            "edr_heuristic": any(
                t.get("source") == "edr_heuristic" for t in entry.get("telemetry", []) or []),
        })
    return {
        "_comment": "NoiseHound automated-calibration plan. Per edge: the abuse primitive to run "
                    "and the event IDs that count as detection. The harness executes each abuse in "
                    "a clean window, counts detect_events in the Security/Sysmon logs, and scores "
                    "detected/runs automatically. edr_heuristic edges also need an EDR/MDI portal check.",
        "version": __version__,
        "edges": edges,
    }


def main(argv: list | None = None) -> int:
    args = build_parser().parse_args(argv)

    try:
        corpus = load_corpus(args.corpus)
    except (FileNotFoundError, ValueError) as exc:
        print("corpus error: %s" % exc, file=sys.stderr)
        return 2

    if args.plan:
        out_json = json.dumps(build_plan(corpus), indent=2, ensure_ascii=False)
        if args.out:
            with open(args.out, "w", encoding="utf-8") as fh:
                fh.write(out_json + "\n")
            print("wrote calibration plan (%d edges) to %s" % (len(corpus), args.out), file=sys.stderr)
        else:
            print(out_json)
        return 0

    if args.template:
        out_json = json.dumps(build_template(corpus), indent=2, ensure_ascii=False)
        if args.out:
            with open(args.out, "w", encoding="utf-8") as fh:
                fh.write(out_json + "\n")
            print("wrote calibration template (%d edges) to %s" % (len(corpus), args.out),
                  file=sys.stderr)
        else:
            print(out_json)
        return 0

    if not args.input:
        print("input error: --input is required (or use --template)", file=sys.stderr)
        return 2

    try:
        with open(args.input, "r", encoding="utf-8") as fh:
            detections = json.load(fh)
    except (FileNotFoundError, json.JSONDecodeError) as exc:
        print("input error: %s" % exc, file=sys.stderr)
        return 2

    profile, records = calibrate(detections, corpus, args.residual, args.smoothing)

    if args.merge:
        try:
            with open(args.merge, "r", encoding="utf-8") as fh:
                base = json.load(fh)
        except (FileNotFoundError, json.JSONDecodeError) as exc:
            print("merge error: %s" % exc, file=sys.stderr)
            return 2
        profile = _merge_profile(base, profile)

    out_json = json.dumps(profile, indent=2, ensure_ascii=False)
    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(out_json + "\n")
        print("wrote calibrated environment profile to %s (%d edges)"
              % (args.out, len(records)), file=sys.stderr)
    else:
        print(out_json)

    if not args.quiet:
        print("\n" + _render_summary(records), file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
