"""Microsoft Defender for Identity (MDI) as a first-class detection source.

MDI is the identity-tier detection most on-prem AD environments actually have, and
it is **tool-agnostic**: its detections fire on the *operation* (directory
replication, Kerberos ticket requests, shadow-credential writes) regardless of the
tool an operator uses. This module maps MDI's coverage onto corpus edges and emits
an environment profile that raises the edges MDI watches - the identity-tier
counterpart to ``noisehound-sigma``.

MDI has two subsystems, kept distinct here:

* **Runtime alerts** (named detections, e.g. "Suspected DCSync attack") - real-time
  detection that raises an edge's noise toward a severity floor. These drive the
  emitted environment profile.
* **Posture / ISPM** (Identity Security Posture assessments) - MDI flags the
  misconfiguration from the directory side. It is *awareness*, not a runtime alert,
  so it is reported but only nudges the score (``--include-posture``).

The catalog below is curated from Microsoft's published MDI detections + ISPM
assessments. It is data, extend it as MDI evolves.
"""
from __future__ import annotations

import argparse
import json
import sys

from . import __version__
from .corpus import load_corpus

# MDI alert severity -> detection floor (runtime, high-fidelity identity alerts).
_SEVERITY_FLOOR = {"medium": 70, "high": 85}
_POSTURE_FLOOR = 55   # MDI is aware from the directory side (not a runtime alert)

# Runtime alerts: MDI named detection -> the corpus edges it fires on, + severity.
MDI_ALERTS = [
    ("Suspected DCSync attack (replication of directory services)",
     ["DCSync"], "high"),
    ("Suspected Kerberoasting",
     ["Kerberoast", "WriteSPN"], "medium"),
    ("Suspected AS-REP Roasting",
     ["ASREPRoast"], "medium"),
    ("Suspected shadow credentials / key-credential abuse",
     ["AddKeyCredentialLink"], "high"),
    ("Suspicious additions to sensitive groups",
     ["AddMember", "AddSelf"], "medium"),
    ("Suspected resource-based / constrained delegation abuse",
     ["AllowedToDelegate", "AllowedToAct", "AddAllowedToAct"], "medium"),
    ("Suspected AD CS certificate abuse (ESC1/ESC8)",
     ["ADCSESC1", "ADCSESC8", "Enroll"], "high"),
    ("Suspected NTLM relay",
     ["CoerceAndRelayNTLMToADCS", "CoerceAndRelayNTLMToLDAP",
      "CoerceAndRelayNTLMToLDAPS", "CoerceAndRelayNTLMToSMB"], "medium"),
    ("Suspected identity theft (pass-the-hash / pass-the-ticket)",
     ["HasSession"], "high"),
]

# Posture / ISPM assessments: MDI flags the misconfiguration -> the edges it maps to.
MDI_POSTURE = [
    ("Remove non-admin accounts with DCSync permissions", ["DCSync"]),
    ("Unsecure Kerberos delegations",
     ["AllowedToDelegate", "AllowedToAct", "AddAllowedToAct"]),
    ("Rotate gMSA / sMSA passwords", ["ReadGMSAPassword", "DumpSMSAPassword"]),
    ("Manage LAPS / local-admin passwords",
     ["ReadLAPSPassword", "SyncLAPSPassword"]),
    ("AD CS misconfigurations (ESC1/3/4/6/7/8)",
     ["ADCSESC1", "ADCSESC3", "ADCSESC4", "ADCSESC6", "ADCSESC7", "ADCSESC8"]),
]


def compute_coverage(corpus, include_posture: bool = False) -> dict:
    """Map MDI coverage onto corpus edges: edge_type -> {score, kind, detection}.

    Only edges present in the corpus are returned; the best (highest) floor wins,
    with runtime alerts always beating posture at equal edges.
    """
    known = {e["edge_type"] for e in corpus}
    coverage: dict = {}

    def _apply(edges, score, kind, detection):
        for et in edges:
            if et not in known:
                continue
            cur = coverage.get(et)
            if cur is None or score > cur["score"]:
                coverage[et] = {"score": score, "kind": kind, "detection": detection}

    for name, edges, severity in MDI_ALERTS:
        _apply(edges, _SEVERITY_FLOOR[severity], "alert", name)
    if include_posture:
        for name, edges in MDI_POSTURE:
            _apply(edges, _POSTURE_FLOOR, "posture", name)
    return coverage


def to_environment_profile(coverage: dict, name: str = "mdi-coverage") -> dict:
    return {
        "_comment": "Generated by noisehound-mdi v%s. adjustments raise edges Microsoft "
                    "Defender for Identity detects toward an identity-tier floor. MDI is "
                    "tool-agnostic (fires on the operation, any tool). Pass with --environment."
                    % __version__,
        "name": name,
        "edr": "MDI",
        "adjustments": {et: info["score"] for et, info in coverage.items()},
    }


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="noisehound-mdi",
        description="Map Microsoft Defender for Identity coverage onto the corpus and "
                    "emit an identity-tier environment profile + coverage report.")
    p.add_argument("--out", "-o", default=None, help="Write the environment profile here.")
    p.add_argument("--corpus", default=None, help="Corpus directory (default: bundled).")
    p.add_argument("--include-posture", action="store_true",
                   help="Also credit MDI posture/ISPM coverage (awareness, lower floor).")
    p.add_argument("--name", default="mdi-coverage", help="Profile name.")
    p.add_argument("--quiet", action="store_true", help="Suppress the coverage report.")
    p.add_argument("--version", action="version", version="noisehound-mdi %s" % __version__)
    return p


def _render_report(corpus, coverage: dict) -> str:
    all_edges = {e["edge_type"] for e in corpus}
    covered = set(coverage)
    lines = ["MDI COVERAGE  %d/%d corpus edges detected by Defender for Identity"
             % (len(covered), len(all_edges)), ""]
    lines.append("Covered (edge -> floor, kind, detection):")
    for et in sorted(coverage, key=lambda e: -coverage[e]["score"]):
        c = coverage[et]
        lines.append("  %-24s %3d  [%-7s]  %s" % (et, c["score"], c["kind"], c["detection"][:44]))
    lines.append("")
    lines.append("Identity-tier gaps - edges MDI does not detect (need audit/EDR/SIEM):")
    gaps = sorted(all_edges - covered)
    lines.append("  " + (", ".join(gaps) if gaps else "(none)"))
    return "\n".join(lines)


def main(argv: list | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        corpus = load_corpus(args.corpus)
    except (FileNotFoundError, ValueError) as exc:
        print("error: %s" % exc, file=sys.stderr)
        return 2

    coverage = compute_coverage(corpus, include_posture=args.include_posture)
    profile = to_environment_profile(coverage, args.name)
    out_json = json.dumps(profile, indent=2, ensure_ascii=False)

    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(out_json + "\n")
        print("wrote MDI coverage profile (%d edges) to %s" % (len(coverage), args.out),
              file=sys.stderr)
    else:
        print(out_json)

    if not args.quiet:
        print("\n" + _render_report(corpus, coverage), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
